import { House, Booking } from './types';

export const INITIAL_HOUSES: House[] = [
  {
    id: 'house-1',
    title: '제주 삼달리 오가닉 홈 가든 & 월넛 인테리어 투어',
    description: '제주의 따뜻한 햇살이 드는 아늑한 삼달리 독채입니다. 호스트가 수년간 직접 가꾼 허브 정원과 유니크한 북유럽 빈티지 월넛 가구 배치 노하우를 집 구경과 함께 상세히 알려드립니다. 웰컴 드링크(한라봉 청귤 티)가 제공됩니다.',
    pricePerVisit: 35000,
    imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80',
    location: '제주특별자치도 서귀포시 성산읍',
    hostId: 'host-jeju',
    hostName: '김민지',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    amenities: ['한라봉 웰컴 티', '정원 조경 팁 제공', '가구 브랜드 리스트 공유', '포토스팟 무료 폴라로이드 촬영', '주차 지원'],
    maxGuests: 4,
    rating: 4.9,
    reviewsCount: 38,
  },
  {
    id: 'house-2',
    title: '북촌 한옥 리노베이션 하우스 온화 (전통과 현대의 가구 매칭 라이프)',
    description: '전통 개량 한옥의 서까래를 그대로 보존하면서, 초현대적인 디자이너 조명과 오브제로 조화를 이룬 북촌의 대표적인 프라이빗 공간입니다. 한옥 리모델링 경험담과 수집된 고가구 매칭 팁을 호스트와 다담을 나누며 얻어가세요.',
    pricePerVisit: 45000,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    location: '서울특별시 종로구 삼청동',
    hostId: 'host-bukchon',
    hostName: '박준형',
    hostAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    amenities: ['명인 다도 티타임', '한옥 리모델링 견적서 공개', '커스텀 조명 가이드', '작품 도슨트 설명', '에어컨 완비'],
    maxGuests: 3,
    rating: 4.85,
    reviewsCount: 24,
  },
  {
    id: 'house-3',
    title: '광안리 하이엔드 테라스 오션 펜트하우스 (하이파이 오디오 청음 & 홈 가드닝)',
    description: '광안대교 오션뷰가 시원하게 내려다보이는 25층 펜트하우스 세대의 인테리어 구경 기회입니다. 실내에 50종 이상의 희귀 열대식물을 조화롭게 배치한 홈 바 및 하이엔드 뱅앤올룹슨 청음 스페이스를 체험하실 수 있습니다.',
    pricePerVisit: 50000,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    location: '부산광역시 수영구 광안해변로',
    hostId: 'host-busan',
    hostName: '이서윤',
    hostAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80',
    amenities: ['하이파이 오디오 청음', '플랜테리어 노하우 북', '에스프레소 커피 제공', '테라스 포토타임', '디자이너 가구 착석 체험'],
    maxGuests: 5,
    rating: 4.95,
    reviewsCount: 89,
  },
  {
    id: 'house-4',
    title: '강릉 안반데기 별빛 오두막 (우드 가구 제작 쇼룸 및 모닥불 집들이)',
    description: '안반데기 고지대 숲속에 조용히 자리 잡은 호스트의 수제 우드 가방 및 가구 디자인 쇼룸 주택입니다. 화로가 활활 타오르는 거실에서 오리지널 빈티지 오크 인테리어의 진수를 구경하고 우드 카빙 노하우를 배워보세요.',
    pricePerVisit: 40000,
    imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80',
    location: '강원도 강릉시 왕산면',
    hostId: 'host-gangneung',
    hostName: '최진우',
    hostAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    amenities: ['모닥불 인테리어 설명', '셀프 우드 카빙 웰컴 키트', '따뜻한 로컬 스튜 제공', '애완동물 동반 하우스', '주차 편리'],
    maxGuests: 3,
    rating: 4.78,
    reviewsCount: 19,
  },
  {
    id: 'house-5',
    title: '서울 홍대 힙스터 작업실 겸 플리마켓 로프트 (업사이클링 소품 인테리어)',
    description: '연남동 골목에 위치한 아티스트 정우진의 복층 작업실입니다. 버려진 산업 오브제를 환상적인 디자인 전등과 소파로 리폼한 이색 업사이클링 인테리어의 결정체입니다. 공간 구경 후 나만의 업사이클링 배치 조언을 받아가세요.',
    pricePerVisit: 30000,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    location: '서울특별시 마포구 연남로',
    hostId: 'host-hongdae',
    hostName: '정우진',
    hostAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    amenities: ['업사이클 소품 리스트', 'LP 오디오 청음', '빈티지 조명 상세 설명', '드립 커피 실습 체험', '기념 스티커 팩 제공'],
    maxGuests: 2,
    rating: 4.67,
    reviewsCount: 42,
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'booking-mock-1',
    houseId: 'house-1',
    houseTitle: '제주 삼달리 오가닉 홈 가든 & 월넛 인테리어 투어',
    houseImage: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80',
    housePricePerVisit: 35000,
    guestId: 'user-current',
    guestName: '김민수 (나)',
    visitDate: '2026-07-10',
    visitTimeSlot: '오후 2시 ~ 오후 4시',
    totalVisitors: 2,
    totalPrice: 70000,
    status: 'confirmed',
    createdAt: '2026-06-18',
  },
  {
    id: 'booking-mock-2',
    houseId: 'house-5',
    houseTitle: '서울 홍대 힙스터 작업실 겸 플리마켓 로프트 (업사이클링 소품 인테리어)',
    houseImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    housePricePerVisit: 30000,
    guestId: 'user-guest-2',
    guestName: '이은지',
    visitDate: '2026-06-25',
    visitTimeSlot: '오전 11시 ~ 오후 1시',
    totalVisitors: 1,
    totalPrice: 30000,
    status: 'pending',
    createdAt: '2026-06-20',
  }
];
