// IMTAM 화면 문구 모음 — 모든 UI 텍스트는 이 파일에서 관리합니다.
export const T = {
  app: {
    loginRequiredError: "로그인이 필요합니다.",
    bookingErrorGeneric: "예약 신청 중 오류가 발생했습니다.",
    searchPlaceholder: "경기도 성남시 분당구 판교원로 82번길",
    roomsLabel: "방 개수",
    rooms1Plus: "방 1개 이상",
    rooms2Plus: "방 2개 이상",
    rooms3Plus: "방 3개 이상",
    rooms4Plus: "방 4개 이상",
    roomsFilterResetAriaLabel: "방 개수 필터 초기화",
    bathroomsLabel: "화장실 개수",
    bathrooms1Plus: "화장실 1개 이상",
    bathrooms2Plus: "화장실 2개 이상",
    bathrooms3Plus: "화장실 3개 이상",
    bathroomsFilterResetAriaLabel: "화장실 개수 필터 초기화",
    areaLabel: "넓이 (평)",
    area10Plus: "10평 이상",
    area20Plus: "20평 이상",
    area30Plus: "30평 이상",
    area40Plus: "40평 이상",
    areaFilterResetAriaLabel: "넓이 필터 초기화",
    noMatchingHouses: "조건에 부합하는 임탐 매물이 없습니다",
    footerCopyright: "© 2026 IMTAM. All rights reserved.",
    loginRequiredTitle: "로그인이 필요한 화면입니다",
    loginRequiredDesc: "예약 내역과 매물 리스팅 관리는 로그인 후 이용할 수 있습니다.",
    loginSignup: "로그인 / 회원가입",
  },
  navbar: {
    findListingsAndTours: "매물 및 임장 찾기",
    myTourBookings: "내 현장 임장 예약",
    myListingsManagement: "내 매물·투어 리스팅 관리",
    userMenuAriaLabel: "사용자 메뉴",
    imtamMember: "임탐 회원",
    logout: "로그아웃",
    loginSignup: "로그인/회원가입",
    mobileListingsTours: "매물 임장",
    mobileBookingHistory: "예약 내역",
    mobileListingsShort: "매물 리스팅",
  },
  auth: {
    fillEmailPassword: "이메일과 비밀번호를 모두 입력해주세요.",
    enterName: "이름을 입력해주세요.",
    passwordMismatch: "비밀번호가 일치하지 않습니다. 다시 확인해주세요.",
    signupComplete: "회원 가입이 완료되었습니다.",
    invalidLogin: "이메일 또는 비밀번호가 올바르지 않습니다.",
    loginSuccess: "로그인 성공",
    processingError: "처리 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    titleSignUp: "IMTAM 가입",
    titleLogin: "IMTAM 로그인",
    usernameLabel: "사용자명 *",
    namePlaceholder: "예: 김성민",
    emailLabel: "이메일 *",
    passwordSetupLabel: "비밀번호 설정 *",
    passwordLabel: "비밀번호 *",
    confirmPasswordLabel: "비밀번호 확인 *",
    submitSignUp: "약관 동의하고 가입하기",
    submitLogin: "IMTAM에 접속",
    hasAccount: "이미 계정이 있으신가요?",
    firstVisit: "첫 방문이신가요?",
    goToLogin: "여기서 로그인",
    goToSignup: "이메일 가입하기",
  },
  houseCard: {
    ownListingBadge: "내 등록 매물 (Owner)",
    inProgressBadge: "임탐 진행중",
    noRatingLabel: "평점 없음",
    roomsPrefix: "방 ",
    bathroomsPrefix: "욕실 ",
    unitSuffix: "개",
    maxGuestsPrefix: "동반 임장 최대 ",
    maxGuestsSuffix: "명",
    tourBookingLabel: "임장 예약 투어",
    areaUnit: "평",
  },
  houseDetail: {
    hostScheduleMissingError: "호스트가 아직 방문 가능 일정을 등록하지 않았습니다.",
    slotFullError: "선택한 시간대는 정원이 마감되었습니다. 다른 시간대를 선택해 주세요.",
    remainingSeatsErrorPrefix: "이 시간대에 남은 자리는 ",
    remainingSeatsErrorSuffix: "명입니다.",
    successTitle: "현장 임장 예약 접수 완료!",
    successMessage1: "공인중개사 및 소유주에게 투어 안내 예약 신청이 실시간 전달되었습니다.",
    successMessage2: "내 현장 임장 예약 목록 탭에서 실시간 확정 상태를 조회하실 수 있습니다.",
    coverImageAltInfix: " - 전경 ",
    prevPhoto: "이전 사진",
    nextPhoto: "다음 사진",
    roomsPrefix: "방 ",
    bathroomsPrefix: "욕실 ",
    unitSuffix: "개",
    areaSuffix: "평 (공급면적)",
    reviewsCountSuffix: "명의 전속 바이어 리뷰 만족도",
    noReviewsYet: "아직 등록된 리뷰가 없습니다",
    verifiedPartnerPrefix: "검증된 중개 파트너 ",
    hostSubtitle: "매물 실소유주 연계 인증 공인 중개 매칭 전문가",
    introTitle: "[임탐 소개]",
    amenitiesTitle: "하이엔드 인테리어 포인트 & 건축 혜택 요소",
    perVisitLabel: " / 임탐 투어 비용",
    noScheduleWarning: "호스트가 아직 방문 가능 일정을 등록하지 않아 예약할 수 없습니다.",
    visitDateLabelPrefix: "소유주 등록 방문일 선택 (",
    visitDateLabelSuffix: "개 일자 조율가능)",
    timeSlotLabel: "소유주 등록 투어 타임을 선택하세요",
    slotClosedText: "· 마감",
    slotRemainingPrefix: "· 남은 자리 ",
    slotRemainingSuffix: "명",
    slotFullMessage: "선택한 시간대는 정원이 마감되었습니다.",
    slotRemainingSummaryPart1: "선택한 시간대 남은 자리 ",
    slotRemainingSummaryPart2: "명 / 정원 ",
    slotRemainingSummaryPart3: "명",
    guestsCountLabel: "동반 임장 실사 인원",
    totalGuestsLabel: "총 동반 참석자",
    guestsUnit: "명",
    guestsInfoPrefix: "중개자나 소유주가 설정한 회차별 쾌적한 동반 인수는 최대 ",
    guestsInfoMiddle: "이며, 선택한 시간대에는 ",
    guestsInfoSuffix: "까지 예약할 수 있습니다.",
    openingFeeLabelPrefix: "임탐 입장 개방료 (₩",
    openingFeeLabelMiddle: " × ",
    openingFeeLabelSuffix: "인)",
    additionalFeeLabel: "추가 수수료",
    noneLabel: "없음",
    tourCostLabel: "임탐 투어 비용",
    submittingLabel: "예약 신청 중...",
    slotFullButtonLabel: "해당 시간대 마감",
    submitButtonLabel: "현장 임탐 희망 예약하기",
    trustLabel: "Zillow-IMTAM 신뢰: 등기 의무 허위 등록 및 불일치시 100% 반환",
  },
  guest: {
    noBookingsTitle: "신청 완료된 현장 임장 및 홈투어 예약이 없습니다.",
    noBookingsDesc: "매물 탐색 목록에서 관심이 가는 하이엔드 오두막 상가, 리노베이션 주택을 찾아 임탐을 제안하고 예약해보세요!",
    tourConfirmed: "투어 가이드 확정",
    pendingApproval: "파트너 승인 대기중",
    cancelledRejected: "임장 거절·취소됨",
    tourCompleted: "임장 가이드 완료",
    visitDateLabel: "지정 구정일",
    visitTimeLabel: "임장 및 면담 시간대",
    accompanyingLabel: "동행 실사단",
    peopleIncludingApplicant: "명 (신청인 포함)",
    receiptDetailTitle: "임장 가이드 & 청구 영수증 상세",
    entryFeeLabel: "임탐 입장 개방료 (₩",
    personSuffix: "인)",
    brokerageFeeLabel: "중개 수수료",
    finalTotalLabel: "최종 정산 합계액",
    myRatingLabel: "내가 남긴 임장 가이드 평점",
    rateGuideLabel: "임장 가이드 별점 평가",
    starAriaSuffix: "점",
    ratingOutOf5: " / 5.0",
    selectRatingPrompt: "별점을 선택하세요",
    registerRating: "별점 평가 등록",
    ratingRegisteredNote: "평가가 등록되었습니다. 매물 평점에 반영됩니다.",
    cancelConfirm: "정말로 이 스페이스 임장 투어 일정을 철회 신청합니까?",
    cancelRequest: "실사 일정 취소(철회) 요청",
  },
} as const;
